# Generated by Django 4.0.5 on 2022-07-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='datetime_cretaed',
            new_name='datetime_created',
        ),
    ]
